terraform {
  required_version = ">= 1.6.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.100.0"
    }

    tls = {
      source  = "hashicorp/tls"
      version = ">= 4.0.0"
    }

    time = {
      source  = "hashicorp/time"
      version = ">= 0.12.0"
    }

    local = {
      source  = "hashicorp/local"
      version = ">= 2.5.0"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}

locals {
  name_prefix_effective = coalesce(var.resource_prefix, var.name_prefix)

  vm_names = [
    for i in range(var.vm_count) : format("%s-vm-%02d", local.name_prefix_effective, i + 1)
  ]

  vm_map = {
    for name in local.vm_names : name => { name = name }
  }

  vm2_names = (
    var.enable_second_subnet
    ? [for i in range(var.vm_count_subnet2) : format("%s-s2-vm-%02d", local.name_prefix_effective, i + 1)]
    : []
  )

  vm_map_subnet2 = {
    for name in local.vm2_names : name => { name = name }
  }

  vm_private_ips_all = merge(
    {
      for k, nic in azurerm_network_interface.nic :
      k => nic.ip_configuration[0].private_ip_address
    },
    {
      for k, nic in azurerm_network_interface.nic_subnet2 :
      k => nic.ip_configuration[0].private_ip_address
    }
  )

  vm_names_sorted = sort(keys(local.vm_private_ips_all))

  mysql_master_name = try(local.vm_names_sorted[0], null)
  mysql_slave_names = (
    length(local.vm_names_sorted) > 1
    ? slice(local.vm_names_sorted, 1, length(local.vm_names_sorted))
    : []
  )

  mysql_master_ip  = local.mysql_master_name != null ? local.vm_private_ips_all[local.mysql_master_name] : null
  mysql_slave_ips  = [for name in local.mysql_slave_names : local.vm_private_ips_all[name]]
  mysql_slaves_ini = length(local.mysql_slave_ips) > 0 ? join("\n", local.mysql_slave_ips) : ""

  ansible_inventory_ini = (
    local.mysql_master_ip == null
    ? ""
    : trimspace(<<-EOT
      # MySQL Ansible inventory (generated by Terraform)

      # 定义主节点 (Master)
      [mysql_master]
      ${local.mysql_master_ip}

      # 定义从节点 (Slaves)
      [mysql_slave]
      ${local.mysql_slaves_ini}

      # 定义一个总组
      [db_servers:children]
      mysql_master
      mysql_slave

      # --- 关键修改区域 ---
      [db_servers:vars]
      # 1. 必须改为 azureuser，因为 Azure 不让 root 直接连
      ansible_user=${var.admin_username}
      mysql_datadir=/data/mysql
      mount_point=/data

      # 2. 指定私钥路径 (如果是默认 ~/.ssh/id_ed25519 可省略，但写上更保险)
      ansible_ssh_private_key_file=~/.ssh/id_ed25519

      # 3. 开启自动提权：连进去后自动执行 sudo 变成 root
      ansible_become=yes
      ansible_become_method=sudo
      ansible_become_user=root
      ansible_become_pass=

      # 额外：避免首次连接交互
      ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    EOT
    )
  )
}

resource "azurerm_resource_group" "rg" {
  name     = var.resource_group_name
  location = var.location
}

resource "local_file" "inventory_ini" {
  filename = "${path.module}/mysql_inventory.ini"
  content  = local.ansible_inventory_ini
}

# Outputs
output "vm_private_ips" {
  value = local.vm_private_ips_all
}

output "vnet_id" { value = azurerm_virtual_network.vnet.id }
output "subnet_id" { value = azurerm_subnet.subnet.id }

output "subnet2_id" { value = try(azurerm_subnet.subnet2[0].id, null) }

output "ansible_inventory_ini" {
  description = "Ansible inventory in INI format (also written to mysql_inventory.ini by local_file)."
  value       = local.ansible_inventory_ini
}

output "ansible_controller_private_ip" {
  description = "Private IP of the Ansible controller VM (only when enable_ansible_controller_vm=true)."
  value       = var.enable_ansible_controller_vm ? azurerm_network_interface.ansible_controller_nic[0].ip_configuration[0].private_ip_address : null
}

output "ansible_controller_vm_name" {
  description = "Name of the Ansible controller VM (only when enable_ansible_controller_vm=true)."
  value       = var.enable_ansible_controller_vm ? azurerm_linux_virtual_machine.ansible_controller[0].name : null
}
